version: "3.7"

services:
  java_db:
    container_name: "java_db"
    image: postgres:11
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    networks:
      - java_db_network
    volumes:
      - "./database/data/:/var/lib/postgresql/data:z"

networks:
  java_db_network:
